### ISSUE TITLE
React route and UI 部分 Sharing 使用到了graphql的内容

### ISSUE THREAD

**Issue by fanyizhe** [JoeShi/ako2020-lucky-money#24]
问题位置：https://lucky-money.lab798.com/3.reactapp/routesandui/

问题1： Sharing 的代码所使用到的graphql代码在当前步骤下还没涉及到，最下面withAuthenticator当前也没涉及到

问题2：Ranking 的代码贴成 sharing 的了

**Comment by JoeShi** [comment]
closed
