### ISSUE TITLE
Add Game Logic - Add function 中 Lambda 代码错误，环境变量错误

### ISSUE THREAD

**Issue by fanyizhe** [JoeShi/ako2020-lucky-money#27]
问题1：Add function 中贴出的 Lambda 代码中图中部分遗漏了前面的 ‘-’
![图片](https://user-images.githubusercontent.com/32582770/72200762-538a7180-3488-11ea-87a3-ac2856b00ee2.png)

问题2：最后 Lambda Environment Varible 步骤，给的命令中：
 
- ENV 应为 env
- USER_POOL_ID 应为 COGNITO_USER_POOL_ID

**Comment by JoeShi** [comment]
resolve
