### ISSUE TITLE
React Routes & Material UI 部分的排版严重错误，缺少 App.js 的代码，红包图片下载 404，ar子页面不显示任何内容

### ISSUE THREAD

**Issue by fanyizhe** [JoeShi/ako2020-lucky-money#7]
问题位置：https://lucky-money.lab798.com/3.reactapp/routesandui/

问题1：代码部分排版严重错误，导致直接复制的话无法通过编译，会有很多错误。

问题2：没有贴出 App.js 的代码

问题3：Create React Components and download assets 部分，最后下载图片那条命令失败，显示 404 Not Found

问题4：部署完代码后在本地运行时，ranking和sharing 能够显示内容，ar 页面没有显示任何内容

**Comment by JoeShi** [comment]
2. 3 已经修复。 

1 目前不清楚原因，后续部署再继续观察
4. 需要重新验证

**Comment by JoeShi** [comment]
1. 已经修复
